# The default context.
[context]
# The proxy URI to request services.
# Comment this line to disable Proxy feature.
# proxy_uri = ""

# Should we retrieve FLAC by default?
# enable_flac = false

# The search mode for waiting the response.
# Can be `fast_first` or `order_first`.
# search_mode = "fast_first"

# The default config for engines.
[context.config]
# "joox:cookie" = "..."
# "qq:cookie" = "..."
# "ytdl:exe" = "..."

# The rate limit configuration
[rate_limit]
# The max requests allowed per duration.
# By default, it is `30` requests.
# max_requests = 30

# The applied duration of the rate limit.
# By default, it is `300` seconds.
# limit_duration_seconds = 300
